/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Lokacija;
import domen.Radnik;
import domen.Raspored;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ModelTabeleRaspored;
import poslovnalogika.Kontroler;

/**
 *
 * @author User
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        srediTabelu();
        popuniLokacije();
        popuniRadnike();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtondodajraspored = new javax.swing.JButton();
        jButtonobrisiraspored = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRaspored = new javax.swing.JTable();
        jButtonsacuvajrasporede = new javax.swing.JButton();
        jComboBoxlokacije = new javax.swing.JComboBox();
        jComboBoxradnici = new javax.swing.JComboBox();
        jTextFieldbrojsati = new javax.swing.JTextField();
        jTextFielddatum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lokacija:");

        jLabel2.setText("Radnik:");

        jLabel3.setText("Broj sati:");

        jLabel4.setText("Datum(dd.MM.yyyy):");

        jButtondodajraspored.setText("Dodaj raspored");
        jButtondodajraspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondodajrasporedActionPerformed(evt);
            }
        });

        jButtonobrisiraspored.setText("Obriši raspored");
        jButtonobrisiraspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonobrisirasporedActionPerformed(evt);
            }
        });

        jTableRaspored.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRaspored);

        jButtonsacuvajrasporede.setText("Sačuvaj rasporede");
        jButtonsacuvajrasporede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsacuvajrasporedeActionPerformed(evt);
            }
        });

        jComboBoxlokacije.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxradnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxradnici, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldbrojsati, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(1, 1, 1)
                                        .addComponent(jTextFielddatum, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtondodajraspored)
                                        .addGap(36, 36, 36)
                                        .addComponent(jButtonobrisiraspored))
                                    .addComponent(jButtonsacuvajrasporede)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(60, 60, 60)
                                        .addComponent(jComboBoxlokacije, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 44, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxlokacije, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxradnici, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldbrojsati, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddatum)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondodajraspored)
                    .addComponent(jButtonobrisiraspored))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonsacuvajrasporede)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtondodajrasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondodajrasporedActionPerformed

        Lokacija lokacija = (Lokacija) jComboBoxlokacije.getSelectedItem();
        Radnik radnik = (Radnik) jComboBoxradnici.getSelectedItem();
        String brsati = null;
        int brojsati = -1;
        try {
            brsati = jTextFieldbrojsati.getText();
            for (int i = 0; i < brsati.length(); i++) {
                if (!Character.isDigit(brsati.charAt(i))) {
                    JOptionPane.showMessageDialog(this, "Broj sati mora biti u ciframa, a ne slovima unet!", "Greska", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            }

            brojsati = Integer.parseInt(brsati);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Broj sati nije unet!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dat = null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = null;
        try {
            dat = jTextFielddatum.getText();
            if (dat.isEmpty()) {
                throw new IllegalArgumentException();
            }
            datum = sdf.parse(dat);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Datum nije unet!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (ParseException ex) {

            JOptionPane.showMessageDialog(this, "Nije dobar format datuma unet!");
            return;
        }
        if (brojsati != -1 && datum != null) {
            Raspored r = new Raspored(-1, brojsati, datum, lokacija, radnik);
            ModelTabeleRaspored mtr = (ModelTabeleRaspored) jTableRaspored.getModel();
            mtr.dodaj(r);
        }
    }//GEN-LAST:event_jButtondodajrasporedActionPerformed

    private void jButtonobrisirasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonobrisirasporedActionPerformed
        try {
            int index = jTableRaspored.getSelectedRow();
            ModelTabeleRaspored mtr = (ModelTabeleRaspored) jTableRaspored.getModel();
            mtr.izbrisi(index);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Niste selektovali red koji zelite da obrisete!");
        }
    }//GEN-LAST:event_jButtonobrisirasporedActionPerformed

    private void jButtonsacuvajrasporedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsacuvajrasporedeActionPerformed
        //1r 1lokacija
        ModelTabeleRaspored mtr = (ModelTabeleRaspored) jTableRaspored.getModel();
        ArrayList<Raspored> listaRasporeda = mtr.vratiListuRaporeda();
        for (int i = 0; i < listaRasporeda.size(); i++) {
            Raspored r1 = listaRasporeda.get(i);
            for (int j = i + 1; j < listaRasporeda.size(); j++) {
                Raspored r2 = listaRasporeda.get(j);
                if (r1.getRadnik().getRadnikID() == r2.getRadnik().getRadnikID()
                        && r1.getLokacija().getLokacijaID() != r2.getLokacija().getLokacijaID()) {
                    JOptionPane.showMessageDialog(this, "1 radnik moze samo na jednoj lokaciji da radi!!", "Greska", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            }

        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        for (int i = 0; i < listaRasporeda.size(); i++) {
            Raspored r1 = listaRasporeda.get(i);
            String dat1 = sdf.format(r1.getDatum());
            int ukang = r1.getBrojSati();
            for (int j = i + 1; j < listaRasporeda.size(); j++) {
                Raspored r2 = listaRasporeda.get(j);
                String dat2 = sdf.format(r2.getDatum());
                if (r1.getRadnik().getRadnikID() == r2.getRadnik().getRadnikID()
                        && dat1.equals(dat2)) {
                    ukang += r2.getBrojSati();
                }

            }
            if (ukang > 8) {
                JOptionPane.showMessageDialog(this, "1 radnik moze samo 8h da radi dnevno!!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        boolean uspesno=Kontroler.getInstance().sacuvaj(listaRasporeda);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Sve uspesno sacuvano!!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        JOptionPane.showMessageDialog(this, "Nista nije sacuvano!!", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);}
    }//GEN-LAST:event_jButtonsacuvajrasporedeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondodajraspored;
    private javax.swing.JButton jButtonobrisiraspored;
    private javax.swing.JButton jButtonsacuvajrasporede;
    private javax.swing.JComboBox jComboBoxlokacije;
    private javax.swing.JComboBox jComboBoxradnici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRaspored;
    private javax.swing.JTextField jTextFieldbrojsati;
    private javax.swing.JTextField jTextFielddatum;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleRaspored mtr = new ModelTabeleRaspored();
        jTableRaspored.setModel(mtr);
        setTitle("[FON] Unos rasporeda");
    }

    private void popuniLokacije() {
        jComboBoxlokacije.removeAllItems();
        ArrayList<Lokacija> listaLokacija = Kontroler.getInstance().vratiListuLokacija();
        for (Lokacija lokacija : listaLokacija) {
            jComboBoxlokacije.addItem(lokacija);
        }
    }

    private void popuniRadnike() {
        jComboBoxradnici.removeAllItems();
        ArrayList<Radnik> listaRadnika = Kontroler.getInstance().vratiListuRadnika();
        for (Radnik radnik : listaRadnika) {
            jComboBoxradnici.addItem(radnik);
        }
    }
}
